# This is a basic workflow to help you get started with Actions

name: shellcheck

# Controls when the action will run. 
on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.0.0
        env:
          SHELLCHECK_OPTS: -e SC2034 -e SC2154 -e SC2129
